name: "Pull Request Updater GitHub Action"
description: "GitHub Action that updates a pull request with information extracted from branch name"
author: "Tamim Khan"
runs:
  using: "node12"
  main: "dist/index.js"
inputs:
  repo-token:
    description: "The GITHUB_TOKEN secret"
    required: true
  base-branch-regex-arr:
    description: "array of regex to match text from the base branch name the regex patterns can be replaced with a tuple [ regex, convertMatchToLowerCase ]['some_snake_case', true] would match 'some_snake_case' but return 'some snake case')"
    required: false
    default: ""
  head-branch-regex-arr:
    description: "Same as base-branch-regex-arr"
    required: false
    default: ""
  title-template:
    description: "Title template where matched text from branch gets substituted in. Allowed tokens: %basebranch% | %headbranch%"
    required: false
    default: ""
  title-update-action:
    description: "Update action to perform on the title. Allowed values: prefix | suffix | replace"
    required: false
    default: "prefix"
  title-insert-space:
    description: "Should insert a space between title and its prefix or suffix"
    required: false
    default: "true"
  body-template:
    description: "Body template where matched text from branch gets substituted in. Allowed tokens: %basebranch% | %headbranch%"
    required: false
    default: ""
  body-update-action:
    description: "Update action to perform on the body. Allowed values: prefix | suffix | replace"
    required: false
    default: "prefix"
  body-newline-count:
    description: "Number of newlines to separate body and its prefix or suffix"
    required: false
    default: "2"
outputs:
  baseMatch:
    description: "Matched text from base branch if any"
  headMatch:
    description: "Matched text from head branch if any"
  titleUpdated:
    description: "Whether the PR title was updated"
  bodyUpdated:
    description: "Whether the PR body was updated"
branding:
  icon: "edit-3"
  color: "green"
