name: "Update Pull Request"

on: pull_request

jobs:
  update_pr:
    runs-on: ubuntu-latest
    outputs:
      baseMatch: ${{ steps.update_pr.outputs.baseMatch }}
      headMatch: ${{ steps.update_pr.outputs.headMatch }}
      titleUpdated: ${{ steps.update_pr.outputs.titleUpdated }}
      bodyUpdated: ${{ steps.update_pr.outputs.bodyUpdated }}
    steps:
      - id: update_pr
        uses: BMCooley/pr-update-action@v3.1.1
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          head-branch-regex-arr: "[\"^\\w-\\d*?(?=_)\", [\"\\?(.*)\", true]]"
          base-branch-regex-arr: "[\"^\\w-\\d*?(?=_)\", [\"\\?(.*)\", true]]"
          title-template: "%head[0]% - %head[1]%"
          body-template: "some:/link/withcardNumber/%base[0]%/%base[1]%"
  update_pr_outputs:
    runs-on: ubuntu-latest
    needs: update_pr
    steps:
      - run: |
          echo 'baseMatch:' ${{needs.update_pr.outputs.baseMatch}}
          echo 'headMatch:' ${{needs.update_pr.outputs.headMatch}}
          echo 'titleUpdated:' ${{needs.update_pr.outputs.titleUpdated}}
          echo 'bodyUpdated:' ${{needs.update_pr.outputs.bodyUpdated}}
